<?php

use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Config\ConfigFactoryInterface;

/**
   *
   * @param array $form
   *   An associative array containing the structure of the form.
   * @param \Drupal\Core\Form\FormStateInterface $form_state
   *   The current state of the form.
   * @param string $form_id
   *   The form id.
   *
   * @see hook_form_alter()
   */
function axelerant_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'system_site_information_settings') {
	$site_api_key = \Drupal::config('axelerant.setting')->get('site_api_key');
	$form['site_information']['site_api_key'] = array(
      '#type' => 'textfield',
      '#title' => t('Site API Key'),
	  '#default_value' => (isset($site_api_key)) ? $site_api_key : '',
      '#description' => t('Site API Key'),
      '#required' => TRUE,
    );
	$form['#validate'][] = 'site_apikey_form_validate';
	$form['#submit'][] = 'site_apikey_form_submit';
	if($site_api_key != '') {
	 $form['actions']['submit']['#value'] = t('Update Configuration');	
	}
	
	return $form;
  }
}

function site_apikey_form_validate(array &$form, FormStateInterface $form_state) {
	if ($form_state->getValue('site_api_key') == '') {
		$form_state->setErrorByName('Site_api_key', t('Please enter the site api key'));
    }
}

function site_apikey_form_submit($form, &$form_state) {  
    \Drupal::configFactory()->getEditable('axelerant.setting')
      ->set('site_api_key', $form_state->getValue('site_api_key'))
      ->save();
	drupal_set_message('Site API Key has been saved '. $form_state->getValue('site_api_key'));  
}

?>